-- TAO DATABASE 
CREATE DATABASE XOMITDB
USE XOMITDB
GO
-- TAO BANG USER
CREATE TABLE USERS
(
	[MATHANHVIEN] VARCHAR(20),
	[TENTHANHVIEN] NVARCHAR(50),
	[MATKHAU] VARCHAR(20),
	[EMAIL] VARCHAR(30),
	[DIACHI] NVARCHAR(MAX),
	[SDT] VARCHAR(13),
	[MACAPBAC] VARCHAR(20),
	CONSTRAINT [PK_MATHANHVIEN] PRIMARY KEY (MATHANHVIEN)
)
GO
-- TAO BANG CAP BAC
CREATE TABLE RANKS
(
	[MACAPBAC] VARCHAR(20),
	[TENCAPBAC] NVARCHAR(30),
	CONSTRAINT [PK_MACAPBAC] PRIMARY KEY (MACAPBAC)
)
GO
-- TAO BANG BAI VIET
CREATE TABLE POSTS
(
	[MABAIVIET] VARCHAR(20),
	[TIEUDE] NVARCHAR(30),
	[NOIDUNG] NVARCHAR(MAX),
	[ANHDAIDIEN] VARCHAR(30),
	[HINHANH] VARCHAR(30),
	[NGAYVIET] DATETIME,
	[MATHANHVIEN] VARCHAR(20),
	[MATHUMUC] VARCHAR(20)
	CONSTRAINT [PK_MABAIVIET] PRIMARY KEY (MABAIVIET)
)
GO
-- TAO BANG BINH LUAN
CREATE TABLE COMMENT
(
	[MABINHLUAN] VARCHAR(20),
	[TIEUDE] NVARCHAR(30),
	[NOIDUNG] NVARCHAR(MAX),
	[ANHDAIDIEN] VARCHAR(30),
	[HINHANH] VARCHAR(30),
	[NGAYVIET] DATETIME,
	[MATHANHVIEN] VARCHAR(20),
	[MABAIVIET] VARCHAR(20),
	[THUTU] INT,
	CONSTRAINT [PK_MABINHLUAN] PRIMARY KEY (MABINHLUAN)
)
GO
-- TAO BANG THU MUC
CREATE TABLE FOLDER
(
	[MATHUMUC] VARCHAR(20),
	[TENTHUMUC] NVARCHAR(30),
	[GHICHU] NVARCHAR(50),
	[LOP] INT,
	CONSTRAINT [PK_THUMUC] PRIMARY KEY (MATHUMUC)
)
GO
-- TAO BANG QUANG CAO
CREATE TABLE ADVERTISE
(
	[MAQUANGCAO] VARCHAR(20),
	[TENQUANGCAO] NVARCHAR(30),
	[CHUTHICH] NVARCHAR(30),
	[VITRI] VARCHAR(30),
	[HINHANH] VARCHAR(30),
	[CHIPHI] FLOAT,
	CONSTRAINT [PK_MAQUANGCAO] PRIMARY KEY (MAQUANGCAO)
)
GO
-- TAO BANG KHACH HANG
CREATE TABLE CUSTOMERS
(
	[MAKHACHHANG] VARCHAR(20),
	[TENKHACHANG] NVARCHAR(50),
	[DIACHI] NVARCHAR(MAX),
	[EMAIL] VARCHAR(30),
	[SDT] VARCHAR(13),
	[MAQUANGCAO] VARCHAR(20),
	CONSTRAINT [PK_MAKHACHHANG] PRIMARY KEY (MAKHACHHANG)
)
GO
-- TAO KHOA NGOAI
-- 1. KHOA NGOAI [MACAPBAC] CUA [USERS] VA [RANKS]
ALTER TABLE [USERS] ADD CONSTRAINT [FK_USERS_RANKS] FOREIGN KEY ([MACAPBAC]) REFERENCES [RANKS] ([MACAPBAC])
GO
-- 2. KHOA NGOAI [MATHANHVIEN] CUA [POSTS] VA [USERS]
ALTER TABLE [POSTS] ADD CONSTRAINT [FK_POSTS_USERS] FOREIGN KEY ([MATHANHVIEN]) REFERENCES [USERS] ([MATHANHVIEN])
GO
-- 3. KHOA NGOAI [MATHUMUC] CUA [POSTS] VA [FOLDER]
ALTER TABLE [POSTS] ADD CONSTRAINT [FK_POSTS_FOLDER] FOREIGN KEY ([MATHUMUC]) REFERENCES [FOLDER] ([MATHUMUC])
GO
-- 4. KHOA NGOAI [MABAIVIET] CUA [COMMENT] VA [POSTS]
ALTER TABLE [COMMENT] ADD CONSTRAINT [FK_COMMENT_POSTS] FOREIGN KEY ([MABAIVIET]) REFERENCES [POSTS] ([MABAIVIET])
GO
-- 5. KHOA NGOAI [MATHANHVIEN] CUA [COMMENT] VA [USERS]
ALTER TABLE [COMMENT] ADD CONSTRAINT [FK_COMMENT_USERS] FOREIGN KEY ([MATHANHVIEN]) REFERENCES [USERS] ([MATHANHVIEN])
GO
-- 6. KHOA NGOAI [MAQUANGCAO] CUA [CUSTOMERS] VA [ADVERTISE]
ALTER TABLE [CUSTOMERS] ADD CONSTRAINT [FK_CUSTOMERS_ADVERTISE] FOREIGN KEY ([MAQUANGCAO]) REFERENCES [ADVERTISE] ([MAQUANGCAO])
GO